#!/bin/sh
bash "$HOME/vinyl/pi/launch-browser.sh" &

# Hide the cursor at startup, then re-hide on every 3s of inactivity.
# Uses labwc's HideCursor action bound to Alt+Super+H (defined in rc.xml).
( sleep 1; wtype -M alt -M logo h -m alt -m logo ) &
swayidle -w timeout 3 'wtype -M alt -M logo h -m alt -m logo' &
